tox-install: &tox-install
  name: Setup tox virtualenv
  command: |
    virtualenv tox-venv || python -m venv tox-venv
    . tox-venv/bin/activate
    pip install tox tox-battery

version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.6
      - test-3.7
jobs:
  test-3.7:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run: *tox-install
      - run:
          name: Run default tests
          command: |
            . tox-venv/bin/activate
            tox -e py37-default -- -s tests/test_self_versioning.py
      - run:
          name: Run gevent-ed tests
          command: |
            . tox-venv/bin/activate
            tox -e py37-gevented
  test-3.6:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run: *tox-install
      - run:
          name: Run default tests
          command: |
            . tox-venv/bin/activate
            tox -e py36-default
      - run:
          name: Run gevent-ed tests
          command: |
            . tox-venv/bin/activate
            tox -e py36-gevented
  test-2.7:
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - run: *tox-install
      - run:
          name: Run default tests
          command: |
            . tox-venv/bin/activate
            tox -e py27-default
      - run:
          name: Run gevent-ed tests
          command: |
            . tox-venv/bin/activate
            tox -e py27-gevented
